services:
  mysql:
    image: mysql:8.0
    container_name: repair-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repair_service
      MYSQL_USER: repair_user
      MYSQL_PASSWORD: repair123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: repair-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/repair_service?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: repair_user
      SPRING_DATASOURCE_PASSWORD: repair123

    depends_on:
      - mysql

volumes:
  mysql_data: